### ISSUE TITLE
Request error! TypeError : this.leaveRoom is not a function 

### ISSUE THREAD

**Issue by hatung** [tiaod/moleculer-io#18]
I got this message when try to leave a array of rooms
```
[2019-03-21T07:07:37.634Z] ERROR 32e7b0baa36c-15/API:    Request error! TypeError : this.leaveRoom is not a function 
 TypeError: this.leaveRoom is not a function
    at Promise.all.ctx.meta.$leave.map.room (/app/node_modules/moleculer-io/lib/index.js:172:64)
    at Array.map (<anonymous>)
    at Service.handler (/app/node_modules/moleculer-io/lib/index.js:172:47)
```

**Comment by tiaod** [comment]
I missed it here, the API changed after version 1.0 . Thanks for report
